gcloud functions deploy generate_api_token \
    --no-gen2 \
    --trigger-http \
    --runtime=python310 \
    --region=southamerica-east1 \
    --source=cloudfuncton_generate_jwt_token \
    --entry-point=main \
    --service-account=currency-converter-collection@fourth-eon-422319-v6.iam.gserviceaccount.com \
    --timeout=60s \
    --memory=512MB \
    --max-instances=10 \
    --env-vars-file=env.yaml